# Submit file to segment images using 2D U-Net

# Must set the universe to Docker
universe = docker
docker_image = docker://nvcr.io/nvidia/pytorch:23.07-py3

# Set the log, error, and output files 
log = predict.log.txt
error = predict.err.txt
output = predict.out.txt

# Set the executable to run
executable = predict.sh
arguments = $(Process)

# Transfer data to the compute node
transfer_input_files = pred_imgs.tar.gz, unet.py, predict.py, data_loading.py, checkpoint_epochXX.pth

# Transfer checkpoints back to submit node
transfer_output_files = pred_masks.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# We require a machine with a compatible version of the CUDA driver
require_gpus = (DriverVersion >= 12.1)

# We must request 1 CPU in addition to 1 GPU
request_cpus = 1
request_gpus = 1

# Select some memory and disk space
request_memory = 20GB
request_disk = 5GB

# Opt in to using CHTC GPU Lab resources
+WantGPULab = true
# Specify short job type: "short", "medium", or "long"
+GPUJobLength = "short"

# Tell HTCondor to run 1 instances of our job:
queue 1
